version: '3.9'
services:
  web:
    image: node:lts
    working_dir: /repository
    depends_on:
      - db
    ports:
      - '3000:4000'
    volumes:
      - ./:/repository
    command: 'npm start'
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - lab-01-db:/var/lib/postgresql/data
volumes:
  lab-01-db: